
backend:
  name: git-gateway
  branch: main

local_backend: true

media_folder: "/src/assets/images" # Location where files will be stored in the repo
public_folder: "/src/assets/images" # The src attribute for uploaded media

collections:
  - name: "artwork"
    label: "Artwork"
    folder: "/src/content/artwork"
    media_folder: "/src/images/gallery/artwork"
    public_folder: "/src/images/gallery/artwork"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields: &artwork_fields
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Size", name: "size", widget: "string", required: false }
      - { label: "Medium", name: "medium", widget: "string", required: false }
      - label: "Categories"
        name: "categories"
        widget: "list"
        default: []
        required: false
      - { label: "Available", name: "available", widget: "boolean", default: false }
      - { label: "Featured", name: "featured", widget: "boolean", default: false }
      - label: "Image"
        name: "image"
        widget: "image"
      - { label: "Description", name: "description", widget: "text", required: false }
